server:
  port: 8081
  servlet:
    context-path: /hujun
limit:
  maxValue: 100
  minValue: 11
  description: 最少${limit.minValue},最多${limit.maxValue}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rubbish_classfication?characterEncoding=utf-8
    username: root
    password: 65093270
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true